# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "wifet74017@kameili.com",
    "password": "password1212",
    "role":"support"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "wifet74017@kameili.com",
    "password": "password1212",
    "role":"support"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
