# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "example@admin.com",
    "password": "password1212",
    "role":"admin"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@user.com",
    "password": "password1212",
    "role":"user"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
