# baseURL
@baseURL = http://localhost:3000

###
# Find All tickets
GET {{ baseURL }}/tickets?category=Performance Problem


###
# Find Ticket By Id
GET {{ baseURL }}/tickets/64a68efb42abf96b7ca39986

###
# Create Ticket
POST {{ baseURL }}/tickets
Content-Type: application/json

{
    "title": "Screen Freeze ",
    "description": "Very bad application , no able to do payment ",
    "priority":"medium",
    "category":"General Inquiry"
}

###
# Modify Ticket By Id
PUT {{ baseURL }}/tickets/64a69836e7da8d9be90fbd44
Content-Type: application/json

{
  "priority":"low"
}

# ###
# # Delete User By Id
# DELETE {{ baseURL }}/users/1
