# baseURL
@baseURL = http://localhost:3000

###
# Find All tickets
GET {{ baseURL }}/tickets

### 
# (support) Get tickets assigned to me
GET {{baseURL}}/tickets/claimed

###
# Find Ticket By Id
GET {{ baseURL }}/tickets/64a91eddee4c35298bbb9c34

###
# Create Ticket
POST {{ baseURL }}/tickets
Content-Type: application/json

{
    "title": "Buggy application ",
    "description": "Lot of Lag while rendering",
    "priority":"high",
    "category":"Performance Problem"
}

###
# Modify Ticket By Id
PUT {{ baseURL }}/tickets/64a91eddee4c35298bbb9c34
Content-Type: application/json

{
  "priority":"low"
}

###
#Claim a Ticket by Id
PUT {{baseURL}}/tickets/claim/64ad50c973eab63175a7d00c
Content-Type: application/json


###
#Reassign a Ticket
PUT {{baseURL}}/tickets/64accf1b8a377592877d764b/reassign
Content-Type: application/json

{
  "agentId":"64acde931e9ccba763a38efa"
}


###
#Close a ticket
PUT {{baseURL}}/tickets/64accd54849dca2daea02246/resolve
Content-Type: application/json


###
# add Comment
POST {{baseURL}}/tickets/comment/64ad50c973eab63175a7d00c
Content-Type: application/json

{
  "text":"Lol! it can be fixed easily."
}