# baseURL
@baseURL = http://localhost:3000

###
# Find All tickets
GET {{ baseURL }}/tickets


###
# Find Ticket By Id
GET {{ baseURL }}/tickets/64a6668e46b332c85fd99394

###
# Create Ticket
POST {{ baseURL }}/tickets
Content-Type: application/json

{
    "title": "Screen Freeze ",
    "description": "Very bad application , no able to do payment ",
    "priority":"medium"
}

# ###
# # Modify User By Id
# PUT {{ baseURL }}/users/1
# Content-Type: application/json

# {
#     "email": "example@email.com",
#     "password": "password"
# }

# ###
# # Delete User By Id
# DELETE {{ baseURL }}/users/1
